### ISSUE TITLE
ragel-7.0.0.12 is not tagged on github

### ISSUE THREAD

**Issue by lu-zero** [adrian-thurston/ragel#50]
Also the tarball provided in the website is missing the test directory.

**Comment by adrian-thurston** [comment]
Hi @lu-zero, I just added the tag. About the test directory ... at that time the tests were not present in the source code repository. All testing was being done from a unified colm networks test suite and it wasn't opensource. I've since added it back so going forward the tests will be distributed with ragel. There has been a bit of a shuffling about of code as I figured out what components belong where.

**Comment by lu-zero** [comment]
Thank you :) The Gentoo ebuild used to run the tests but now I removed that part for the time being.
