### ISSUE TITLE
Unused-variable issue

### ISSUE THREAD

**Issue by behdad** [adrian-thurston/ragel#56]
With ragel-7.0.0 (which unfortunately Fedora ships) I'm seeing:
```
hb-ot-shape-complex-use-machine.rl:195:15: error: unused variable ‘act’
[-Werror=unused-variable]
```
Inspecting the generated code, I see `act` is actually unused.

We also see whitespace and other seemingly unnecessary changes compared to previous versions. In case interested: https://github.com/harfbuzz/harfbuzz/pull/2723

**Comment by adrian-thurston** [comment]
Hi @bedad, you can remove `act` from the list of declared variables in your driver code. In ragel 7 it's use is eliminated if not needed in order to perform a correct scan. In ragel 6 I was always referencing it, but compilers started more and more noticing it was not actually needed. If you change the regular language definitions in your scanner you may need to add it back.

**Comment by adrian-thurston** [comment]
The code generation technique was completely redone in ragel 7. Some code and whitespace changes should be expected. The two are meant to be compatible though in terms of how the generated code functions.
